# main:main.cc
# 	g++ -std=c++17 $^ -o $@ -lgtest -lgtest_main -pthread
# test1:test1.cc
# 	g++ -std=c++17 $^ -o $@ -lgtest -lgtest_main -pthread
# test2:test2.cc
# 	g++ -std=c++17 $^ -o $@ -lgtest -lgtest_main -pthread
test3:test3.cc
	g++ -std=c++17 $^ -o $@ -lgtest -lgtest_main -pthread